# Generated by Django 3.2.3 on 2021-05-16 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_qunatity_orderitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='porduct',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
