# Generated by Django 3.2.3 on 2021-05-16 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_porduct_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='transaaction_id',
            new_name='transaction_id',
        ),
    ]
