# Generated by Django 3.2.3 on 2021-05-17 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_rename_transaaction_id_order_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='porduct',
            name='price',
            field=models.FloatField(),
        ),
    ]
