# Generated by Django 3.2.3 on 2021-05-18 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20210518_1137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='Phone',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='profile_pic',
        ),
    ]
